name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    # - name: Install Theos
    - uses: Randomblock1/theos-action@v1.4
    - name: make
      run: make
    - name: package
      run: make package

